language: CSharp
install:
  - nuget restore -source "https://www.nuget.org/api/v2/;https://api.nuget.org/v3/" AllAcu.sln
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.k/kvm/kvm.sh
  - kvm upgrade
  - kpm restore --no-cache
solution: AllAcu.sln
script_windows: .\PreBuild.ps1
